const API_TYPE = {
  LOGIN: 'LOGIN',
  REGISTER: 'REGISTER',
  CHECK_AUTH: 'CHECK_AUTH',

  GET_RECIPES: 'GET_POSTS',
  GET_RECIPE: 'GET_POST',
  POST_RECIPE: 'POST_POST',
  PUT_RECIPE: 'PUT_POST',
  DELETE_RECIPE: 'DELETE_POST',
};
export default API_TYPE;
